imgbasePath: "." # Base path for images

searchTypes: # List of supported search types
  - regex

directories:
  - dir: "tests/store"
    fileTypes: # Key can be * or ommitted for all files.
      - md


